ControleProdutosQ3/Controllers/ClienteController.cs
using ControleProdutosQ3.Models;
using ControleProdutosQ3.Repository;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace ControleProdutosQ3.Controllers
{
    public class ClienteController : Controller
    {
        private readonly IClienteRepositorio _clienteRepositorio;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ClienteController(IClienteRepositorio clienteRepositorio, IWebHostEnvironment webHostEnvironment)
        {
            _clienteRepositorio = clienteRepositorio;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            List<ClienteModel> clientes = await _clienteRepositorio.BuscarTodos();

            return await Task.FromResult(View(clientes));
        }

        public async Task<IActionResult> Criar()
        {
            return await Task.FromResult(View());
        }

        [HttpPost]
        public async Task<IActionResult> Criar(ClienteModel cliente, IFormFile? imagemCarregada, string bairro, string cidade, string logradouro) 
        {
           
            if(!ValidaModels.Valida<ClienteModel>(cliente))
            {
                return await Task.FromResult(View(cliente));
            }


            if (imagemCarregada == null)
            {
                cliente.Foto = null;
                cliente.NomeDaFoto = "";
            }
            else
            {
                cliente.Foto = Util.SalvaImagem(imagemCarregada, _webHostEnvironment.WebRootPath);
                cliente.NomeDaFoto = imagemCarregada.FileName;
            }

            cliente.Enderecos.Add(new EnderecoModel
            {
                Bairro = bairro,
                Logradouro = logradouro,
                Cidade = cidade,
                ClienteId = cliente.Id,
                CEP = cliente.CEP

            });


            await _clienteRepositorio.Adicionar(cliente);

            return await Task.FromResult(RedirectToAction("Index"));
        }

        public async Task<IActionResult> Alterar(ClienteModel cliente, IFormFile imagemCarregada)
        {


            if (!ValidaModels.Valida<ClienteModel>(cliente))
            {
                return await Task.FromResult(View(cliente));
            }


            if (imagemCarregada == null)
            {
                cliente.Foto = null;
                cliente.NomeDaFoto = "";
            }
            else
            {
                cliente.Foto = Util.SalvaImagem(imagemCarregada, _webHostEnvironment.WebRootPath);
                cliente.NomeDaFoto = imagemCarregada.FileName;
            }

           


            await _clienteRepositorio.Editar(cliente);

            return await Task.FromResult(RedirectToAction("Index"));
           
        }

        public async Task<IActionResult> Editar(long id)
        {
            ClienteModel cliente = await _clienteRepositorio.BuscarPorId(id);
            return await Task.FromResult(View(cliente));
        }

        public async Task<IActionResult> Atualizar(long id)
        {
            ClienteModel cliente = await _clienteRepositorio.BuscarPorId(id);
            cliente.Ativo = !cliente.Ativo;
            await _clienteRepositorio.Editar(cliente);
            return await Task.FromResult(RedirectToAction("Index"));

        }

        public async Task<IActionResult> ApagarConfirmacao(long id)
        {
            ClienteModel cliente = await _clienteRepositorio.BuscarPorId(id);
            return await Task.FromResult(View(cliente));

        }

        public async Task<IActionResult> Remover(long id)
        {
            ClienteModel cliente = await _clienteRepositorio.BuscarPorId(id);
            await _clienteRepositorio.Apagar(cliente);

            return await Task.FromResult(RedirectToAction("Index"));

        }

    }
}

ControleProdutosQ3/Controllers/LoginController.cs
using ControleProdutosQ3.Models;
using ControleProdutosQ3.Repository;
using Microsoft.AspNetCore.Mvc;

namespace ControleProdutosQ3.Controllers
{
    public class LoginController : Controller
    {
        public const string SessionKeyUser = "_Usuario";
        public const string SessionKeyEmail = "_Email";
        public const string SessionKeyNivel = "_Nivel";
        public const string SessionKeyId = "_Id";

        private readonly ILoginRepositorio _loginRepositorio;

        public LoginController(ILoginRepositorio loginRepositorio) 
        {
            this._loginRepositorio = loginRepositorio;
        }

        public async Task<IActionResult> Index()
        {
            return await Task.FromResult(View());
        }

        public async Task<IActionResult> Registro()
        {
            return await Task.FromResult<IActionResult>(View());
        }


        [HttpPost]
        public async Task<IActionResult> Registro(LoginModel login, string? senha)
        {
            LoginModel loginDB = login;
            loginDB.Senha = Util.Criptografia(senha! ?? "123");

            loginDB.NivelAcesso = 1;
            loginDB.DataRegistro = DateTime.Now;
            loginDB.Ativo = true;
            loginDB.EmailConfirmado = false;
            loginDB.TelefoneConfirmado = false;

            await _loginRepositorio.Adicionar(loginDB);

            return await Task.FromResult(RedirectToAction("Index", "Home"));
        }

        [HttpPost]
        public async Task<IActionResult> Index(string usuario, string senha)
        {
            LoginModel loginDB = await _loginRepositorio.ListarPorUsuario(usuario);
            var sucesso = false;

            if (loginDB.Usuario != null && senha != null) 
            {
                sucesso = Util.Decriptografia(loginDB.Senha, senha);
            }

            if (sucesso)
            {
                // Gravando usuario logado na sessão

                HttpContext.Session.SetString(SessionKeyUser, loginDB.Usuario);
                HttpContext.Session.SetString(SessionKeyEmail, loginDB.Email);
                HttpContext.Session.SetInt32(SessionKeyNivel, loginDB.NivelAcesso);
                HttpContext.Session.SetInt32(SessionKeyId, (int) loginDB.Id);

				return await Task.FromResult(RedirectToAction("Index", "Home"));


			}

            return await Task.FromResult(View());
        }


		async public Task<IActionResult> Editar(long id)
		{
			LoginModel login = await _loginRepositorio.ListarPorId(id);

			return await Task.FromResult(View(login));
		}


		[HttpPost]
		public async Task<IActionResult> Alterar(LoginModel login, string senhaAtual, string novaSenha)
		{
			LoginModel loginDB = await _loginRepositorio.ListarPorId(login.Id);

			if (loginDB != null)
			{
				if (novaSenha != null)
				{
					var sucesso = false;
					sucesso = Util.Decriptografia(loginDB.Senha, senhaAtual);

					if (sucesso)
					{
						loginDB.Senha = Util.Criptografia(novaSenha);
					}
				}
				else
				{
					loginDB.Senha = loginDB.Senha;
				}
				loginDB.Usuario = login.Usuario;
				loginDB.Email = login.Email;
				loginDB.NivelAcesso = login.NivelAcesso;

				await _loginRepositorio.Atualizar(loginDB);
				return await Task.FromResult(RedirectToAction("Sair", "Home"));
			}

			return await Task.FromResult(View());
		}

	}
}

ControleProdutosQ3/Controllers/ProdutoController.cs
using ControleProdutosQ3.Models;
using ControleProdutosQ3.Repository;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace ControleProdutosQ3.Controllers
{
    public class ProdutoController : Controller
    {

        //Injeção de dependência
        private readonly IProdutoRepositorio _produtoRepositorio;

        private readonly IWebHostEnvironment _environment;

        public ProdutoController(IProdutoRepositorio produtoRepositorio, IWebHostEnvironment environment)
        {
            _produtoRepositorio = produtoRepositorio;
            _environment = environment;
        }

        public async Task<IActionResult> Index()
        {
            List<ProdutoModel> produtos = await _produtoRepositorio.BuscarTodos();
            return await Task.FromResult(View(produtos));
        }

        public async Task<IActionResult> Criar()
        {
            return await Task.FromResult(View());
        }

        public async Task<IActionResult> Editar(long id)
        {
            ProdutoModel produto = await _produtoRepositorio.BuscarPorId(id);   
            return await Task.FromResult(View(produto));
        }

        [HttpPost]
        public async Task<IActionResult> Alterar(ProdutoModel produto, IFormFile? imagemCarregada, DateTime dataAlterada)
        {


            bool isValid = ValidaModels.Valida(produto);
            if (!isValid)
            {

                return await Task.FromResult(RedirectToAction("Editar", produto));

            }

            if (imagemCarregada != null)
            {
                produto.Foto = Util.SalvaImagem(imagemCarregada, _environment.WebRootPath);
                produto.NomeDaFoto = Path.GetFileName(imagemCarregada!.FileName);
            }
            else
            {
                produto.Foto = null;
                produto.NomeDaFoto = "";
            }


            produto.DataDeValidade = dataAlterada;

            await _produtoRepositorio.Atualizar(produto);
            return await Task.FromResult(RedirectToAction("Index"));
        }

        [HttpPost]
        public async Task<IActionResult> Criar(ProdutoModel produto, IFormFile? imagemCarregada)
        {
            
            bool isValid = ValidaModels.Valida(produto);
            if (!isValid)
            {
                
                return await Task.FromResult(View(produto));
                
            }

            if (imagemCarregada != null)
            {
                produto.Foto = Util.SalvaImagem(imagemCarregada, _environment.WebRootPath);
                produto.NomeDaFoto = Path.GetFileName(imagemCarregada!.FileName);
            }
            else
            {
                produto.Foto = null;
                produto.NomeDaFoto = "";
            }

            produto.DataDeRegistro = DateTime.Now;

            await _produtoRepositorio.Adicionar(produto);

            return await Task.FromResult(RedirectToAction("Index"));
        }

        public async Task<IActionResult> ApagarConfirmacao(long id)
        {
            ProdutoModel produto = await _produtoRepositorio.BuscarPorId(id);
            return await Task.FromResult(View(produto));
        }


        public async Task<IActionResult> Remover(long id)
        {
            ProdutoModel produto = await _produtoRepositorio.BuscarPorId(id);
            await _produtoRepositorio.Apagar(produto);
            return await Task.FromResult(RedirectToAction("Index"));
        }

        public async Task<IActionResult> AlterarEstado(long id)
        {
            ProdutoModel produto = await _produtoRepositorio.BuscarPorId(id);

            produto.Ativo = !produto.Ativo;

            await _produtoRepositorio.Atualizar(produto);
            return await Task.FromResult(RedirectToAction("Index"));

        }

    }
}

ControleProdutosQ3/Views/Shared/_Layout.cshtml
@using ControleProdutosQ3.Controllers;
@{
    var usuario = Context.Session.GetString(LoginController.SessionKeyUser);
    var idUsuario = Context.Session.GetInt32(LoginController.SessionKeyId);
}


<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Controle de Produtos Q3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ControleProdutosQ3.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Trainee.NET</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <div>
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            @if(usuario != null)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produtos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                                </li>
                            }
                        </ul>
                    </div>
                    <div>
                        <ul class="navbar-nav flex-grow-1">
                            @if(usuario == null)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Entrar</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Editar" asp-route-id=@idUsuario>@usuario</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Sair">Sair</a>
                                </li>
                            }
                        </ul>
                    </div>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Controle de Produtos Q3 - <a asp-area="" asp-controller="Produto" asp-action="Index">Produtos</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>