ControleProdutosQ3/Controllers/ClienteController.cs
using ControleProdutosQ3.Models;
using ControleProdutosQ3.Repository;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace ControleProdutosQ3.Controllers
{
    public class ClienteController : Controller
    {
        private readonly IClienteRepositorio _clienteRepositorio;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ClienteController(IClienteRepositorio clienteRepositorio, IWebHostEnvironment webHostEnvironment)
        {
            _clienteRepositorio = clienteRepositorio;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            List<ClienteModel> clientes = await _clienteRepositorio.BuscarTodos();

            return await Task.FromResult(View(clientes));
        }

        public async Task<IActionResult> Criar()
        {
            return await Task.FromResult(View());
        }

        [HttpPost]
        public async Task<IActionResult> Criar(ClienteModel cliente, IFormFile? imagemCarregada, string bairro, string cidade, string logradouro) 
        {
           
            if(!ValidaModels.Valida<ClienteModel>(cliente))
            {
                return await Task.FromResult(View(cliente));
            }


            if (imagemCarregada == null)
            {
                cliente.Foto = null;
                cliente.NomeDaFoto = "";
            }
            else
            {
                cliente.Foto = Util.SalvaImagem(imagemCarregada, _webHostEnvironment.WebRootPath);
                cliente.NomeDaFoto = imagemCarregada.FileName;
            }

            cliente.Enderecos.Add(new EnderecoModel
            {
                Bairro = bairro,
                Logradouro = logradouro,
                Cidade = cidade,
                ClienteId = cliente.Id,
                CEP = cliente.CEP

            });


            await _clienteRepositorio.Adicionar(cliente);

            return await Task.FromResult(RedirectToAction("Index"));
        }

        public async Task<IActionResult> Alterar(ClienteModel cliente, IFormFile imagemCarregada)
        {


            if (!ValidaModels.Valida<ClienteModel>(cliente))
            {
                return await Task.FromResult(View(cliente));
            }


            if (imagemCarregada == null)
            {
                cliente.Foto = null;
                cliente.NomeDaFoto = "";
            }
            else
            {
                cliente.Foto = Util.SalvaImagem(imagemCarregada, _webHostEnvironment.WebRootPath);
                cliente.NomeDaFoto = imagemCarregada.FileName;
            }

           


            await _clienteRepositorio.Editar(cliente);

            return await Task.FromResult(RedirectToAction("Index"));
           
        }

        public async Task<IActionResult> Editar(long id)
        {
            ClienteModel cliente = await _clienteRepositorio.BuscarPorId(id);
            return await Task.FromResult(View(cliente));
        }

        public async Task<IActionResult> Atualizar(long id)
        {
            ClienteModel cliente = await _clienteRepositorio.BuscarPorId(id);
            cliente.Ativo = !cliente.Ativo;
            await _clienteRepositorio.Editar(cliente);
            return await Task.FromResult(RedirectToAction("Index"));

        }

        public async Task<IActionResult> ApagarConfirmacao(long id)
        {
            ClienteModel cliente = await _clienteRepositorio.BuscarPorId(id);
            return await Task.FromResult(View(cliente));

        }

        public async Task<IActionResult> Remover(long id)
        {
            ClienteModel cliente = await _clienteRepositorio.BuscarPorId(id);
            await _clienteRepositorio.Apagar(cliente);

            return await Task.FromResult(RedirectToAction("Index"));

        }

    }
}

ControleProdutosQ3/Controllers/EnderecoController.cs
using ControleProdutosQ3.Models;
using ControleProdutosQ3.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using System.ComponentModel.DataAnnotations;

namespace ControleProdutosQ3.Controllers
{
    public class EnderecoController : Controller
    {

        public const string SessionKeyUser = "_Usuario";
        public const string SessionKeyEmail = "_Email";
        public const string SessionKeyNivel = "_Nivel";



        private readonly IEnderecoRepositorio _enderecoRepositorio;

        public EnderecoController(IEnderecoRepositorio endereco) 
        { 
            this._enderecoRepositorio = endereco;
        }


        public async Task<IActionResult> Index()
        {

            List<EnderecoModel> enderecos = await _enderecoRepositorio.BuscarTodos();

            var usuario = HttpContext.Session.GetString(SessionKeyUser);
            if (!usuario.IsNullOrEmpty()) return await Task.FromResult(View(enderecos));
            
            return await Task.FromResult(RedirectToAction("Index", "Home"));
        }

        [HttpGet]
        public async Task<IActionResult> EnderecosCliente(long clienteId)
        {
            List<EnderecoModel> enderecos = await _enderecoRepositorio.BuscarTodos();
            var enderecosFiltrados = enderecos.Where(endereco => endereco.ClienteId == clienteId);
            var usuario = HttpContext.Session.GetString(SessionKeyUser);
            if (!usuario.IsNullOrEmpty()) return await Task.FromResult(View(enderecosFiltrados));

            return await Task.FromResult(RedirectToAction("Index", "Home"));
        }


        public async Task<IActionResult> Criar()
        {
            return await Task.FromResult(View());
        }

        public async Task<IActionResult> Editar(long id)
        {
            return await Task.FromResult(View(await _enderecoRepositorio.ListarPorId(id)));
        }

        public async Task<IActionResult> ApagarConfirmacao(long id)
        {
            EnderecoModel endereco = await _enderecoRepositorio.ListarPorId(id);

            return await Task.FromResult(View(endereco));
        }

        public async Task<IActionResult> Apagar(long id)
        {

            await _enderecoRepositorio.Apagar(id);
            return await Task.FromResult(RedirectToAction("Index"));

        }

        [HttpPost]
        public async Task<IActionResult> Criar(EnderecoModel endereco)
        {
            if (ValidaModels.Valida(endereco))
            {
                return View(endereco);
            }

            await _enderecoRepositorio.Adicionar(endereco);

            return await Task.FromResult(RedirectToAction("Index"));
        }

        [HttpPost]
        public async Task<IActionResult> Alterar(EnderecoModel endereco)
        {
            await _enderecoRepositorio.Atualizar(endereco);
            return await Task.FromResult(RedirectToAction("Index"));

        }


    }
}

ControleProdutosQ3/Views/Cliente/ApagarConfirmacao.cshtml
@model ClienteModel

@{
    ViewData["Title"] = "Confirmação da Exclusão do Produto";
}
<div class="text-center">
    <h3 class="display-4">Deseja Realmente Excluir o Produto @Model.Nome?</h3>
</div>
<div class="container d-flex justify-content-center">
    <a class="btn btn-primary btn-block" role="button" asp-controller="Cliente" asp-action="Index">Cancelar Exclusão</a>
    <a class="btn btn-danger btn-block" role="button" asp-controller="Cliente" asp-action="Remover" asp-route-id="@Model.Id">Confirmar Exclusão</a>
</div>

ControleProdutosQ3/Views/Cliente/Criar.cshtml
@model ClienteModel

@{
    ViewData["Title"] = "Cadastro de cliente";
}

<div class="row col-10 mx-auto mt-4">
    <form asp-controller="Cliente" asp-action="Criar" enctype="multipart/form-data" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="col-sm-4">
            <label for="cpf" class="form-label">CPF</label>
            <input type="text" asp-for="CPF" class="form-control" id="cpf" placeholder="CPF" />
            <span asp-validation-for="CPF" class="text-danger"></span>
        </div>


        <div class="col-sm-4">
            <label for="nome" class="form-label">Nome</label>
            <input type="text" asp-for="Nome" class="form-control" id="nome" placeholder="Nome" />
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>
        <div class="col-sm-4">
            <label for="sobrenome" class="form-label">Sobrenome</label>
            <input type="text" asp-for="Sobrenome" class="form-control" id="sobrenome" placeholder="Sobrenome" />
            <span asp-validation-for="Sobrenome" class="text-danger"></span>
        </div>
        <div class="col-sm-4">
            <label for="telefone" class="form-label">Número de Contato</label>
            <input type="text" asp-for="Telefone" class="form-control" id="telefone" placeholder="DDD + número" />
            <span asp-validation-for="Telefone" class="text-danger"></span>
        </div>
        

        <div class="col-sm-4">
            <label for="cep" class="form-label">CEP</label>
            <input type="text" asp-for="CEP" class="form-control" id="cep" placeholder="CEP" />
            <span asp-validation-for="CEP" class="text-danger"></span>
        </div>

        <div class="col-sm-4">
            <label class="form-label" for="logradouro">Logradouro</label>
            <input class="form-control" type="text" id="logradouro" name="logradouro" placeholder="Digite o logradouro"/>
        </div>

        <div class="col-sm-4">
            <label class="form-label" for="bairro">Bairro</label>
            <input class="form-control" type="text" id="bairro" name="bairro" placeholder="Digite o bairro" />
        </div>

        <div class="col-sm-4">
            <label class="form-label" for="cidade">Cidade</label>
            <input class="form-control" type="text" id="cidade" name="cidade" placeholder="Digite o nome da cidade" />
        </div>

        <div class="col-sm-4">
            <label class="form-label" for="nomeDaFoto">Foto</label>
            <input class="form-control" type="file" accept="image/png, image/jpeg" id="nomeDaFoto"  name="imagemCarregada" />
        </div>

        <div class="form-check">
            <input class="form-check-label" type="checkbox" id="situacao" asp-for="Ativo" />
            <label class="form-check-label" for="situacao">Ativo</label>
        </div>

        <div>
            <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
        </div>
    </form>
</div>

ControleProdutosQ3/Views/Cliente/Editar.cshtml
@model ClienteModel

@{
    ViewData["Title"] = "Editar cliente";
}

<div>
    <form asp-controller="Cliente" asp-action="Alterar" enctype="multipart/form-data" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div>
            <label for="id" class="form-label">ID do Cliente</label>
            <input type="number" asp-for="Id" class="form-control" id="id" placeholder="0" />
            <span asp-validation-for="Id" class="text-danger"></span>
        </div>
        <div>
            <label for="nome" class="form-label">Nome do Cliente</label>
            <input type="text" asp-for="Nome" class="form-control" id="nome" placeholder="Nome" />
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>
        <div>
            <label for="telefone" class="form-label">Número de Contato</label>
            <input type="text" asp-for="Telefone" class="form-control" id="telefone" placeholder="DDD + número" />
            <span asp-validation-for="Telefone" class="text-danger"></span>
        </div>
        
        <div class="form-check">
            <input class="form-check-label" type="checkbox" id="situacao" asp-for="Ativo" />
            <label class="form-check-label" for="situacao">Ativo</label>
        </div>
        <div>
            <label for="nomeDaFoto" class="form-label">Imagem do produto: </label>
            @Html.DisplayFor(model => model.NomeDaFoto)
            <input type="file" accept="image/png, image/jpeg" class="form-control" id="nomeDaFoto" placeholder="Busque a foto do produto." name="imagemCarregada" />
        </div>
        <div>
            <button type="submit" class="btn btn-primary btn-block">Confirmar</button>
        </div>
    </form>
</div>

ControleProdutosQ3/Views/Cliente/Index.cshtml
@model List<ClienteModel>

@{
    ViewData["Title"] = "Clientes";
    var imgSrc = "https://cdn-icons-png.flaticon.com/512/5360/5360776.png";
}

<div class="text-center">

    <div class="d-sm-inline-flex justify-content-between" style="column-gap: 1vh">
        <a class="btn btn-success" role="button" asp-controller="Cliente" asp-action="Criar">
            Adicionar novo Cliente
        </a>
    </div>

    <div>
        <h2>Listar Clientes</h2>      
    </div>

    <table class="table caption-top">
        <caption>Lista de Produtos</caption>
        <thead>
            <tr>
                <th scope="col">Foto</th>
                <th scope="col">Id</th>
                <th scope="col">Nome</th>
                <th scope="col">Sobrenome</th>
                <th scope="col">CPF</th>
                <th scope="col">Telefone</th>
                <th scope="col">Endereços</th>
                <th scope="col">Situação</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>

            @if (Model != null && Model.Any())
            {
                foreach (ClienteModel cliente in Model)
                {

                    string situacao = cliente.Ativo ? "Ativo" : "Inativo";

                    if(cliente.Foto != null)
                    {
                        var base64 = Convert.ToBase64String(cliente.Foto);
                        imgSrc = $"data:image/gif;base64,{base64}";
                    }
                    else
                    {
                        imgSrc = "https://cdn-icons-png.flaticon.com/512/5360/5360776.png";
                    }


                    <tr class="align-baseline">
                        <td scope="col"><img src="@imgSrc" width="50px" height="50px" /></td>
                        <th>@cliente.Id</th>
                        <td>@cliente.Nome</td>
                        <td>@cliente.Sobrenome</td>
                        <td>@cliente.CPF</td>
                        <td>@cliente.Telefone</td>
                        <td>
                            <a role="button" class="mx-2" asp-controller="Endereco" asp-action="EnderecosCliente" asp-route-id="@cliente.Id"><i class="fa-solid fa-house"></i></a>
                        </td>
                        <td>@situacao</td>
                        <td>
                            <div class="btn-group d-flex justify-content-around justify-items-center" role="group">
                                <a role="button" class="mx-2" asp-controller="Cliente" asp-action="Editar" asp-route-id="@cliente.Id"><i class="fa-solid fa-pen-to-square" style="color: #008031;"></i></a>
                                <a role="button" class="mx-2" asp-controller="Cliente" asp-action="Atualizar" asp-route-id="@cliente.Id"><i class="fa-solid fa-eye-slash" style="color: #ccb100;"></i></a>
                                <a role="button" class="mx-2" asp-controller="Cliente" asp-action="ApagarConfirmacao" asp-route-id="@cliente.Id"><i class="fa-solid fa-trash" style="color: #e60000;"></i></a>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>